name: BlockPiglinsTranformation
version: 1.1
main: com.ssomar.blockpiglinstransformation.BlockPiglinsTransformation
api-version: 1.16
author: Ssomar
description: Block the transformation of the Piglins